name = "gic-website"
compatibility_date = "2024-08-18"
compatibility_flags = ["nodejs_compat"]

# Pages configuration
pages_build_output_dir = "out"

[env.production]
name = "gic-website"

[env.preview]
name = "gic-website-preview"

# KV namespace for contact form submissions
[[env.production.kv_namespaces]]
binding = "GIC_CONTACT"
id = "your-kv-namespace-id"

[[env.preview.kv_namespaces]]
binding = "GIC_CONTACT"
id = "your-preview-kv-namespace-id"

# Environment variables for production
[env.production.vars]
ENVIRONMENT = "production"
NODE_ENV = "production"

# Environment variables for preview
[env.preview.vars]
ENVIRONMENT = "preview"
NODE_ENV = "development"